package view;

import dao.CursoDAO;
import model.Curso;
import table.CursoTableModel;


public class CadastroCurso extends javax.swing.JFrame {
    
    Curso curso = new Curso();
    CursoDAO cursoDao = new CursoDAO();

    /**
     * Creates new form CadastroCurso
     */
    public CadastroCurso() {
        initComponents();
        setLocationRelativeTo(null);
        jtCurso.setModel(new CursoTableModel(new CursoDAO().listarTodos()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfCodCurso = new javax.swing.JTextField();
        jtfDescricaoCurso = new javax.swing.JTextField();
        jtfEmentaCurso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCurso = new javax.swing.JTable();
        jbSalvarCurso = new javax.swing.JButton();
        jbExcluirCurso = new javax.swing.JButton();
        jbCancelarCurso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Descrição");

        jLabel3.setText("Ementa");

        jtfCodCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodCursoActionPerformed(evt);
            }
        });

        jtfDescricaoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDescricaoCursoActionPerformed(evt);
            }
        });

        jtfEmentaCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEmentaCursoActionPerformed(evt);
            }
        });

        jtCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCursoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtCurso);

        jbSalvarCurso.setText("Salvar");
        jbSalvarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarCursoActionPerformed(evt);
            }
        });

        jbExcluirCurso.setText("Excluir");
        jbExcluirCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirCursoActionPerformed(evt);
            }
        });

        jbCancelarCurso.setText("Cancelar");
        jbCancelarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbCancelarCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluirCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalvarCurso))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23)
                        .addComponent(jtfCodCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfEmentaCurso)
                            .addComponent(jtfDescricaoCurso))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfCodCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfDescricaoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfEmentaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvarCurso)
                    .addComponent(jbExcluirCurso)
                    .addComponent(jbCancelarCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCodCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodCursoActionPerformed

    private void jtfEmentaCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEmentaCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEmentaCursoActionPerformed

    private void jbExcluirCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirCursoActionPerformed
        int linha = jtCurso.getSelectedRow();
        Object registroSelecionado = jtCurso.getValueAt(linha, 0);
        cursoDao.excluir((int)registroSelecionado);
    }//GEN-LAST:event_jbExcluirCursoActionPerformed

    private void jbCancelarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCancelarCursoActionPerformed

    private void jtfDescricaoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDescricaoCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDescricaoCursoActionPerformed
    
    
    private void jbSalvarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarCursoActionPerformed
        curso.setDescricao(jtfDescricaoCurso.getText());
        curso.setEmenta(jtfEmentaCurso.getText());
        cursoDao.inserir(curso);
    }//GEN-LAST:event_jbSalvarCursoActionPerformed

    private void jtCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCursoMouseClicked
        jtfCodCurso.setText(jtCurso.getValueAt(jtCurso.getSelectedRow(), CursoTableModel.COL_CODIGO).toString());
        jtfDescricaoCurso.setText(jtCurso.getValueAt(jtCurso.getSelectedRow(), CursoTableModel.COL_DESCRICAO).toString());
        jtfEmentaCurso.setText(jtCurso.getValueAt(jtCurso.getSelectedRow(), CursoTableModel.COL_EMENTA).toString());
    }//GEN-LAST:event_jtCursoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancelarCurso;
    private javax.swing.JButton jbExcluirCurso;
    private javax.swing.JButton jbSalvarCurso;
    private javax.swing.JTable jtCurso;
    private javax.swing.JTextField jtfCodCurso;
    private javax.swing.JTextField jtfDescricaoCurso;
    private javax.swing.JTextField jtfEmentaCurso;
    // End of variables declaration//GEN-END:variables
}
